---
title: "wanting_35507071_TaskD"
author: "Wanting Echo Zhao"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE)
```

# Question 1

## **Mind map**

- Finding differences between faculties and sexes. - get these two columns. change it to factor format, instead of numeral data.
- Extract them to a individual data set for further test.
- Think about the ways of comparing difference between multiple groups. - t test, Anova test.



```{r}
library(tidyverse)
# Load data and extract two target columns. set them as factors
ind <- read.csv("TaskD_Dataset/forum_ind_train.csv", stringsAsFactors = F)
ind$demographic_sex <- factor(ind$demographic_sex)
ind$unit_faculty <- factor(ind$unit_faculty)

head(ind$demographic_sex)
head(ind$unit_faculty)
ind |> count(demographic_sex)


# Set the LIWC variables = everything except ID and the 2 categoricals.
liwc_vars <- setdiff(names(ind), c("Unique_ID", "unit_faculty", "demographic_sex"))

#  ===== SEX ======
# There are only 2 'X',5 'NA', drop them directly.
sex_df <- ind[ind$demographic_sex %in% c("F", "M"), ] 
sex_df$demographic_sex <- droplevels(sex_df$demographic_sex) # droplevel() remove value not 'F' or 'M'

sex_results <- data.frame()
for (v in liwc_vars) {
  # two-sample t-test
  tt <- t.test(sex_df[[v]] ~ sex_df$demographic_sex)  
  # `sex_df[[v]]` extracts the numerical data for the current language variable `v`. 
  # `~ sex_df$demographic_sex` splits that data into two groups based on sex
  sex_results <- rbind(sex_results, data.frame(
    variable = v,
    mean_F = tt$estimate[1], mean_M = tt$estimate[2],
    diff = tt$estimate[1] - tt$estimate[2], p_value = tt$p.value))
}
sex_results$p_adj <- p.adjust(sex_results$p_value, method = "BH")  # correct for 93 tests
sex_results <- sex_results[order(sex_results$p_adj), ]  # most significant first
head(sex_results, 10)



```

